# -*- coding: utf-8 -*-
"""spotify_attributes_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GmmpSAzg-a3dtrVpzn0UCPRMmBLRa9G0
"""

import pandas as pd


df = pd.read_csv("Spotify_Song_Attributes.csv")

df.dropna(subset=['artistName', 'genre', 'msPlayed', 'danceability','energy','key','loudness','mode','speechiness','acousticness','instrumentalness','liveness','valence','tempo','type','id','uri','track_href','analysis_url','duration_ms','time_signature'], inplace=True)  # Drop rows with missing critical values

df.drop_duplicates(inplace=True)

for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].astype(str).str.lower().str.strip()

df.columns = [col.strip().lower().replace(" ", "_") for col in df.columns]
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
numeric_cols = df.select_dtypes(include=['number']).columns
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])
df = df.apply(lambda x: x.str.encode('utf-8').str.decode('utf-8') if x.dtype == "object" else x)

print(df)

df.to_csv("cleaned_dataset.csv", index=False)

print("Dataset cleaned and saved as 'cleaned_dataset.csv'")

print(df.head())